# Generated by Django 2.2.4 on 2019-09-11 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('housemanage', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='house',
            name='user',
        ),
        migrations.RemoveField(
            model_name='house',
            name='visible',
        ),
        migrations.CreateModel(
            name='HouseDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('housepk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='housemanage.House')),
            ],
        ),
    ]
